project:
  type: website

website:
  title: "ltj"
  favicon: assets/favicon.png
  navbar:
    search: true
    right:
      - text: "teaching"
        href: content/teaching.qmd
      - text: "coding"
        href: content/coding.qmd
      - text: "journal"
        href: content/posts.qmd

  sidebar:
    - title: "teaching"
      contents:
      - content/teaching.qmd
      - content/teaching/philosophy.qmd
      - auto: content/teaching/courses
      - auto: content/teaching/methods
      collapse-level: 1
    - title: "coding"
      contents:
      - content/coding.qmd
      - auto: content/coding/norns
      - auto: content/coding/iii
      collapse-level: 1

# only using ObservableJS cells
execute: 
  eval: true
  echo: false

engine: markdown

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc-title: 'on this page'
    grid:
      margin-width: 300px
    footnotes-hover: false
    citations-hover: true
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js"
    title-block-style: plain

callout-icon: false
code-annotations: hover
reference-location: margin
citation-location: document
bibliography: references.bib